name: Deno

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  denofmt-and-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/checkout@v4

      - run: deno lint
      - run: deno fmt --check

  check:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/checkout@v4

      - run: deno cache *.ts
      - run: deno check *.ts
